export const Images={
splash:require('./../Images/splash.jpg'),
menu:require('./../Images/menu.png'),
search:require('./../Images/search.png'),
time:require('./../Images/time.png'),
backArrow:require('./../Images/backArrow.png'),
nextArrow:require('./../Images/next-arrow.png'),
addNote:require('./../Images/add_note.png'),
addLeads:require('./../Images/add-leads-bg.png'),
filterVertical:require('./../Images/filter_vertical.png'),
delete:require('./../Images/delete.png'),
editYellow:require('./../Images/edit_yellow.png'),
Home:require('./../Images/home_icon.png'),
state:require('./../Images/view_state.png'),
people:require('./../Images/people.png'),
user:require('./../Images/user_visit.png'),
dropdown:require('./../Images/all-dropdown.png'),
sms:require('./../Images/sms-blue.png'),
pencil_note:require('./../Images/pin_edit_icon.png'),
plus_note:require('./../Images/pin_add_icon.png'),
notes:require('./../Images/lead-notes.png'),
Tasks:require('./../Images/lead-task.png'),
Appointment:require('./../Images/lead-appointment.png'),
sms_sent:require('./../Images/sent_sms.png'),
email_white:require('./../Images/emai_white.png'),
calender:require('./../Images/calendar.png'),
cancel:require('./../Images/cancel.png'),
clock_circular:require('./../Images/clock-circular.png'),
graph:require('./../Images/graph.png'),
percentage:require('./../Images/percentage.png'),
set_alarm:require('./../Images/set-alarm.png'),
task_note:require('./../Images/task_note.png'),
warning:require('./../Images/warning.png'),
task_cicle:require('./../Images/Task_circle.png'),
pencil_box:require('../../assets/box_pencil.jpg'),
plus_box:require('../../assets/plus_note.jpg'),
home_navigation:require('./../Images/home.png'),
lead:require('./../Images/leads.png'),
// lead:require('./../Images/leads.png'),
logout:require('./../Images/logout.png'),
settings:require('./../Images/settings.png'),
tags:require('./../Images/tags.png'),
tasks_navigation:require('./../Images/tasks.png'),

}

